execute pathogen#infect()
inoremap kj <ESC>
let mapleader = "\<Space>"
filetype plugin indent on
syntax on
set encoding=utf-8
set ruler
set t_Co=256
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set laststatus=2
set tabstop=2
set shell=/bin/bash
set nocompatible
set number
set colorcolumn=79

colorscheme solarized
set background=dark

